### ISSUE TITLE
High dpi support.

### ISSUE THREAD

**Issue by Superdanby** [facebook-atom/atom-ide-ui#194]
### Description
Fonts in Symbol References tab are small. It'd be great if we can adjust the font. 

### Actual Behavior
Font size is set to 12px Symbol References tab.

### Versions
* Atom: 1.25.0
* Client OS: Fedora 27
* atom-ide-ui: 0.9.4

### Additional Details
* Installed packages (`apm ls --installed`):
├── activate-power-mode@2.7.0 (disabled)
├── atom-ide-ui@0.9.4
├── atom-material-syntax@1.0.8
├── atom-material-ui@2.1.3
├── autoclose-html@0.23.0
├── autocomplete-clang@0.11.4
├── autocomplete-python@1.10.5
├── busy-signal@1.4.3
├── color-picker@2.2.5
├── file-icons@2.1.18
├── fonts@3.0.3
├── git-plus@7.10.2
├── git-time-machine@1.5.9
├── highlight-selected@0.13.1
├── ide-bash@1.0.10
├── ide-cpp@0.0.3
├── ide-flowtype@0.22.1
├── ide-java@0.8.2
├── ide-json@0.2.1
├── ide-php@0.7.14
├── ide-python@0.9.2
├── ide-typescript@0.7.6
├── intentions@1.1.5
├── linter@2.2.0
├── linter-flake8@2.3.0
├── linter-gcc@0.7.1
├── linter-javac@1.9.4
├── linter-markdown@5.2.0
├── linter-ui-default@1.7.1
├── markdown-themeable-pdf@1.2.1
├── markdown-writer@2.7.3
├── minimap@4.29.8
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-linter@2.1.3
├── pdf-view@0.67.0
├── platformio-ide-terminal@2.8.1
├── restart-atom@0.2.0
├── split-diff@1.5.2
├── sunset@1.2.1 (disabled)
├── sync-settings@0.8.6
├── teletype@0.11.0
├── terminal-tab@0.5.5 (disabled)
└── youtube-pane@2.0.0

**Comment by Superdanby** [comment]
Thanks! I get it working with this:
```css
// stom-ide-ui
.datatip-overlay {
    font-size: 20px;
    pre {
        font-size: 16px;
    }
    // atom-text-editor {
    //     font-size: 20px;
    //     line-height: 20px;
    //     width: 500px;
    // }
}

.find-references-file {
    font-size: 18px;
    atom-text-editor {
        font-size: 20px !important;
    }
}

```

![image](https://user-images.githubusercontent.com/17717083/38224928-e7e8800a-3724-11e8-99d2-cd1a562bbf5e.png)

![image](https://user-images.githubusercontent.com/17717083/38225071-b36047f4-3725-11e8-8641-fbed51ea03e0.png)

But what does `.datatip-overlay atom-text-editor` do? Should I not comment it out?
