### ISSUE TITLE
Outline pane using wrong font

### ISSUE THREAD

**Issue by garrettw** [facebook-atom/atom-ide-ui#258]
### Description
After inspecting the CSS behind the outline pane, I can't figure out why it's using the font I have set for the main editor area rather than the font Atom uses for all other UI elements.
I found this:
```css
.outline-view-core {
    font-size: var(--editor-font-size);
    font-family: var(--editor-font-family);
}
```
... which should inherit from this (and the inspector seems to think it already does):
```css
atom-workspace {
    --editor-font-size: 14px;
    --editor-font-family: Menlo, Consolas, DejaVu Sans Mono, monospace;
}
```
but somehow that's not happening visually.

### Expected Behavior
Outline pane should successfully inherit `<atom-workspace>` font.

### Actual Behavior
Outline pane uses same font as `<atom-text-editor>` .

### Versions
* Atom: 1.27.2 x64
* Client OS: macOS High Sierra 10.13.4
* atom-ide-ui: 0.12.0

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (51)
├── aligner@1.2.4
├── aligner-css@1.2.1
├── aligner-javascript@1.3.0
├── aligner-php@1.2.0
├── aligner-scss@1.3.1
├── atom-beautify@0.32.5
├── atom-debug-ui@1.0.4
├── atom-ide-ui@0.12.0
├── atom-material-syntax@1.0.8
├── atom-material-ui@2.1.3
├── atom-twig@4.2.0
├── better-git-blame@0.4.6
├── block-comment-plus@0.5.1
├── double-tag@1.5.0
├── drupal@1.9.2
├── editorconfig@2.2.2
├── firacode@0.3.0
├── git-control@0.9.0
├── git-log@0.4.1
├── git-plus@7.10.2
├── ide-css@0.3.0
├── ide-html@0.4.2
├── ide-json@0.2.1
├── ide-php@0.7.14
├── ide-typescript@0.7.6
├── ide-yaml@0.4.3
├── indent-guide-improved@1.4.13
├── intentions@1.1.5
├── language-blade@0.40.0
├── minimap@4.29.8
├── minimap-codeglance@0.4.7
├── minimap-split-diff@0.3.7
├── nms-color-bracket@0.1.0
├── pep-syntax@0.0.7
├── pep-ui@0.0.5
├── php-composer-completion@0.3.4
├── php-debug@0.3.5
├── php-hyperclick@1.2.1
├── php-ide-serenata@4.1.2
├── php-integrator-refactoring@1.4.1 (disabled)
├── php-integrator-symbol-viewer@0.6.4
├── pigments@0.40.2
├── project-manager@3.3.6
├── seti-syntax@1.1.3
├── seti-ui@1.10.0
├── split-diff@1.5.2
├── symbols-tree-nav@0.15.5 (disabled)
├── symbols-tree-view@0.14.0 (disabled)
├── tab-close@2.1.0
├── tabs-to-spaces@1.0.5
└── unfancy-file-icons@0.11.0
```
