### ISSUE TITLE
Datatip styling could use some padding for tables

### ISSUE THREAD

**Issue by Gert-dev** [facebook-atom/atom-ide-ui#98]
### Description
I'm trying to migrate my own tooltips/datatips to the datatip provider from atom-ide-ui. Datatips already support markdown, which is very neat and I've managed to get this working. However, I now noticed that tables originating from my markdown could use some additional padding between them. An example:

![screenshot](https://user-images.githubusercontent.com/24809863/31736875-379266b4-b446-11e7-94a6-a3b66cc25ef5.png)

The columns in `Parameters` pack rather tightly together. Previously, I just spaced them with some plain CSS, but this isn't possible with datatips anymore without resolving to a full custom React component:

Some copy-pastable code, but I'm not a designer, so use at your own risk 😄.

```css
table {
    margin-left: 1.5em;
    margin-bottom: 1em;

    tr {
        td {
            padding-right: 1em;
            padding-bottom: 0.25em;
            vertical-align: top;
        }
    }
}
```

### Expected Behavior
Some more padding would be added.

### Actual Behavior
No padding is present.

### Versions
* Atom: 1.21.0
* Client OS: Linux
* atom-ide-ui: 0.5.1
